### ISSUE TITLE
"Integer expected" error

### ISSUE THREAD

**Issue by Nielswps** [DEIS-Tools/H-Uppaal#28]
The error is displayed whenever trying to run queries.

I have been looking into the exception generating the message, and it seems to originate from the _parseInteger_ method within the _Parser_ class (line 58). The method calls the _nextToken_ method, which returns 2, causing the _parseInteger_ method to throw the exception.

The exception is caught on line 155 in the _Engine_ class and thrown as an _EngineException_.

All the classes mentioned above are part of the _model.jar_ file located within the _libs_ folder and originate from UPPAAL. The method called from H-UPPAAL causing the exception is located on line 150 in the _UPPAALDriver_ class. The input is a _UppaalSystem_ object, which is generated based on the _HUPPAALDocument_ generated for the project. This also happens within the _Engine_ class inside the _model.jar_ and is assumed be handled correctly, hence the element closest to the exception handled by H-UPPAAL is the _UPPAALDocument_ generated inside the _HUPPAALDocument_ class.

I have also discovered that the 10. Semester project mentioned that H-UPPAAL was compiled using UPPAAL version 4.1.19 (from 2014). Using this version, a “Syntax error” is shown instead of the “Bug: Integer expected” error. This error is given within the _parseProlog_ method inside the _Parser_ class.

**Comment by ghost** [comment]
I haven't seen that error before. Do you still have the diagrams that produced the `Integer expected` error? If you zip the files and attach them to this PR, I'll take a look at the problem.

**Comment by Nielswps** [comment]
I am unable to recreate the error, after trying on both Windows and Ubuntu with two different sample projects, so I assume that it is no longer an issue. I will close this issue
