### ISSUE TITLE
Export XML version

### ISSUE THREAD

**Issue by ulriknyman** [DEIS-Tools/H-Uppaal#33]
Create an "Export as XML" version in the File menu.
This should create an XML version of the project and bring up a file chooser where the file name can be selected.

Note: The functionality to create the actual XML version should already exist as it was created by the students originally working on the project.

**Comment by Nielswps** [comment]
I have checked a number of possible placements for the functionality and have run code analysis to check for unused methods but did not have any luck finding the XML export functionality. There is currently a method for exporting the UPPAALDocument as an XML file, which is saved to the debug folder and named _debug.xml_. Do you know where the functionality could be placed?

**Comment by ulriknyman** [comment]
Hi Niels. I think the "method for exporting the UPPAALDocument as an XML file" is exactly the one we are looking for. You just need to change it such that the user can specify the location in which to save.

**Comment by Nielswps** [comment]
Perfect, should I add a dropdown item to the "File" menu, allowing the user to do so, or should the "Save UPPAAL model" just prompt the user for a location?

**Comment by ulriknyman** [comment]
Thinking about it I think we should have two options in the file menu.
"Export Uppaal model"  <- saves the Uppaal model outside the folder containing the current project naming it "the same as the project folder".xml
"Export Uppaal model as ..." <- Opens file menu prompting user for file name

**Comment by Nielswps** [comment]
Okay, the current implementation is executed by pressing the icon furthest to the right (a box with a downward pointing arrow inside of it), but I personally think the two options inside the "File" dropdown menu is more user friendly, so I will do that as my next PR
