### ISSUE TITLE
Create release 1.0.6

### ISSUE THREAD

**Issue by ghost** [DEIS-Tools/H-Uppaal#44]
The last release of H-UPPAAL was made in 2017, and there's been made quite a few changes since then. 226 commits to be exact.
I suggest [creating a new release](https://github.com/DEIS-Tools/H-Uppaal/releases/new), such that users won't be downloading [a zip archive](https://github.com/DEIS-Tools/H-Uppaal/releases/tag/1.0.5) with a three year old version of the program.

I think it would be best to create the release after you've had a look at #40, #41, #42 and #43, in case you'd like to bring in those changes.

**Comment by sillydan1** [comment]
[v1.0.6](https://github.com/DEIS-Tools/H-Uppaal/releases/tag/1.0.6) release has been made. Closing
