### ISSUE TITLE
Save and Save As does not work for new projects 

### ISSUE THREAD

**Issue by MBSource** [DEIS-Tools/H-Uppaal#45]
**Summary:**
Save and SaveAs returns "no such file" when saving a new project.

**Steps to Reproduce:**
- Create a new project (File->New Project)
- Add a component
- Save the project (File -> Save or Save As)
- Prick a random location, say a new folder in downloads.
- Press save

**Expected results:**
The project is saved.

**Actual results:**
No such file or directory exception is thrown. Unable to save project error is displayed in GUI.

**Comment by sillydan1** [comment]
Solved in https://github.com/DEIS-Tools/H-Uppaal/pull/50
